name: photomood
description: PhotoMood - дневник настроения через фото
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Navigation
  table_calendar: ^3.0.9
  cupertino_icons: ^1.0.6
  fl_chart: ^0.66.0
  shimmer: ^3.0.0
  file_picker: ^5.0.0
  cross_file: ^0.3.0

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2 

  # Data & Storage
  sqflite: ^2.3.0
  path: ^1.8.3
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  localstorage: ^6.0.0
  universal_html: ^2.2.1 

  # Utilities
  crypto: ^3.0.3
  archive: ^3.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true