name: photomood
description: PhotoMood - дневник настроения через фото
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  geolocator: ^11.0.0
  geocoding: ^2.1.3
  http: ^1.1.0  # Для запросов к API погоды

  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.1
  permission_handler: ^11.0.1

  # State Management
  provider: ^6.1.2
  # UI & Navigation
  table_calendar: ^3.2.0
  cupertino_icons: ^1.0.6
  fl_chart: ^0.66.0
  shimmer: ^3.0.0
  image_picker: ^1.0.4
  cross_file: ^0.3.0
  pull_to_refresh: ^2.0.0

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # Data & Storage
  sqflite: ^2.3.0
  path: ^1.8.3
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"        # ← ДОБАВЬТЕ ЭТУ СТРОКУ
  flutter_native_splash: "^2.3.10"         # ← ДОБАВЬТЕ ЭТУ СТРОКУ

flutter:
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/icon_foreground.png"

flutter_native_splash:
  color: "#6A11CB"
  image: "assets/splash/splash.png"
  android: true
  ios: true
  web: false
  android_12:
    color: "#6A11CB"
    image: "assets/splash/splash.png"
    icon_background_color: "#6A11CB"